name: AncientForge
version: 0.15
main: com.podts.ancientforge.P
author: [flatbmx]
softdepend: [PermissionsEx, Essentials]

commands:
  ancientforge:
    description: Main reference command for AncientForge.
    aliases: [af]