name: AncientForge
version: 0.12
main: com.podts.ancientforge.P
author: [flatbmx]
softdepend: [PermissionsEx, Essentials]

commands:
  ancientforge:
    description: Main reference command for AncientForge.
    aliases: [af]
  magicitem:
    description: Gives person a random magic item.